# frozen_string_literal: true

# Everything the browsing pages need to show the API call behind them.
module BrowseHelper
  API_BASE = "https://dogapi.dog/api/v2"

  # The payload is generated by the serializers the API itself uses, so what a
  # page shows and what the endpoint returns cannot drift apart.
  def api_payload(record, serializer)
    serializer.new(record).serializable_hash.deep_stringify_keys
  end

  # A collection payload trimmed to a couple of records: the point is the
  # shape, and a page of 48 breeds would bury it.
  def api_collection_payload(records, serializer, keep: 2)
    payload = serializer.new(records.first(keep)).serializable_hash.deep_stringify_keys
    payload.merge("meta" => {"pagination" => {"records" => records.respond_to?(:size) ? records.size : nil}.compact})
  end

  # Pages are linked by slug, and fall back to the API's own id for anything
  # whose name does not survive being parameterized.
  def breed_path_for(breed) = breed_path(breed.name.parameterize.presence || breed.id)

  def group_path_for(group) = group_path(group.name.parameterize.presence || group.id)

  def api_url(path, params = {})
    query = params.compact.map { |key, value| "#{key}=#{value}" }.join("&")

    [API_BASE, path].join + (query.present? ? "?#{query}" : "")
  end

  # Links to the operation in the reference, using the anchors the docs page
  # already generates from the OpenAPI document.
  def api_docs_url(anchor) = "#{api_v2_path}##{anchor}"

  # Says something specific about this breed rather than about the API, which
  # is the whole point of a per page description.
  def breed_meta_description(breed)
    parts = ["#{breed.name}: a #{breed.group.name.sub(/ Group\z/, "")} breed"]
    parts << "living #{breed_life_span(breed)}" if breed_life_span(breed)
    parts << "weighing #{breed_weight(breed, :male)}" if breed_weight(breed, :male)
    parts << "hypoallergenic" if breed.hypoallergenic

    "#{parts.join(", ")}. #{breed.description}".squish
  end

  # Paged and searched lists are variations of one page. The first page is the
  # address that counts; later pages point at themselves so they stay indexable
  # in their own right.
  def breeds_canonical_path(page, query)
    return breeds_path if query.present? || page.to_i <= 1

    breeds_path(page: {number: page})
  end

  # Enough for a search engine to show the picture and its credit. Schema.org
  # has no dog breed type, so `Thing` carries the name and description and the
  # images do the rest.
  def breed_structured_data(breed)
    {
      "@context" => "https://schema.org",
      "@type" => "Thing",
      "name" => breed.name,
      "description" => breed.description,
      "url" => "#{request.base_url}#{breed_path_for(breed)}",
      "image" => breed.breed_images.map { |image| image_structured_data(image) },
      "isPartOf" => {
        "@type" => "Collection",
        "name" => breed.group.name,
        "url" => "#{request.base_url}#{group_path_for(breed.group)}"
      }
    }.compact_blank
  end

  def image_structured_data(image)
    {
      "@type" => "ImageObject",
      "contentUrl" => image.url_for(:large),
      "thumbnailUrl" => image.url_for(:thumb),
      "license" => image.license_url,
      "creditText" => image.author,
      "creator" => image.author && {"@type" => "Person", "name" => image.author},
      "acquireLicensePage" => image.page_url
    }.compact
  end

  def group_structured_data(group, breeds)
    {
      "@context" => "https://schema.org",
      "@type" => "CollectionPage",
      "name" => group.name,
      "url" => "#{request.base_url}#{group_path_for(group)}",
      "hasPart" => breeds.map do |breed|
        {"@type" => "Thing", "name" => breed.name, "url" => "#{request.base_url}#{breed_path_for(breed)}"}
      end
    }
  end

  def breed_life_span(breed)
    return if breed.life_min.blank? && breed.life_max.blank?

    "#{[breed.life_min, breed.life_max].compact.join("–")} years"
  end

  def breed_weight(breed, sex)
    breed_measurement(breed, "#{sex}_weight", "kg")
  end

  def breed_height(breed, sex)
    breed_measurement(breed, "#{sex}_height", "cm")
  end

  def breed_measurement(breed, field, unit)
    min = breed.public_send("#{field}_min")
    max = breed.public_send("#{field}_max")
    return if min.blank? && max.blank?

    "#{[min, max].compact.join("–")} #{unit}"
  end

  # Where the breed comes from, as one line: "Japan, Akita Prefecture (17th century)".
  def breed_origin(breed)
    country = [breed.origin_country, breed.origin_region].compact_blank.join(", ")
    return if country.blank?

    breed.origin_era.present? ? "#{country} (#{breed.origin_era})" : country
  end

  def breed_coat(breed)
    parts = [breed.coat_length, breed.coat_type].compact_blank.uniq
    colors = Array(breed.coat_colors).compact_blank
    return if parts.empty? && colors.empty?

    [parts.join(" "), colors.to_sentence].compact_blank.join(" · ")
  end

  # The four numbers people came for, pulled out of the details list so they
  # can be read at a glance rather than found in a table.
  def breed_stats(breed)
    [
      breed_stat(:ruler, "Height", breed_height(breed, :male), breed_height(breed, :female)),
      breed_stat(:weight, "Weight", breed_weight(breed, :male), breed_weight(breed, :female)),
      breed_stat(:heart_pulse, "Life span", breed_life_span(breed)),
      breed_stat(:activity, "Exercise", breed_exercise(breed))
    ].compact
  end

  # `rows` is either one plain value or one per sex — never a headline value
  # with a smaller footnote under it, since both sexes are equally the answer.
  def breed_stat(icon, label, value, female = nil)
    return if value.blank? && female.blank?

    rows =
      if value.present? && female.present? && value != female
        [{sex: :mars, value: value}, {sex: :venus, value: female}]
      else
        [{value: value.presence || female}]
      end

    {icon: icon, label: label, rows: rows}
  end

  def breed_exercise(breed)
    minutes = breed.traits_exercise_minutes
    "#{minutes} min/day" if minutes.present?
  end

  def breed_ratings(breed)
    Breed::RATINGS.filter_map do |name|
      value = breed.traits[name.to_s]
      [name.to_s.humanize, value] if value.present?
    end
  end

  # A rating means nothing without the scale it sits on, so it renders as five
  # segments rather than as the bare number.
  def breed_rating_segments(value)
    Array.new(5) { |index| index < value.to_i }
  end

  # The host, not the page title: a row of "akc.org, fci.be, wikipedia.org"
  # says where the facts came from in a glance, where a row of full titles is
  # three lines of text nobody reads.
  def breed_source_label(source)
    URI.parse(source["url"]).host.to_s.delete_prefix("www.").presence || source["url"]
  rescue URI::InvalidURIError
    source["url"]
  end
end
